#!/usr/bin/env bash
# Function to display usage information
usage() {
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
}

# Check if the number of parameters is less than 4
if [ $# -ne 4 ]; then
    usage
fi

# Assign parameters to variables
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

# Perform the file transfer using scp with strict host key checking disabled
scp -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"
