#!/usr/bin/env bash
# install nginx
sudo apt-get update -y
sudo apt-get install nginx -y
CONFIG_FILE="/etc/nginx/sites-available/default"

echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/not_found_page_404.html

# Backup the original configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Create a new configuration file with the desired changes
sudo bash -c "cat > $CONFIG_FILE" <<EOF

server {

	listen 80;

	server_name sshifts.tech;

	root /var/www/html;
	index index.html;
	add_header X-Served-By \$hostname;

	location /redirect_me {
    	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

}
EOF
sudo nginx -s reload
sudo service nginx restart
