#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely
trap 'echo "I am invincible!!!"; interrupted=true' SIGTERM

interrupted=false

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
